use anyhow::Result;
use chrono::{TimeZone, Utc};
use std::path::Path;

use crate::db::Memory;

/// Ceiling on the whole generated file.
///
/// IRONMEM.md is imported by CLAUDE.md, so an assistant reads all of it at the
/// start of every session in this project. That makes its size a recurring
/// charge rather than a one-off: bytes here are paid again on every session,
/// whether or not anything in them turns out to be relevant. Nothing is lost
/// by trimming, because every memory remains in the store and reachable
/// through `search_memories` and `get_context`.
const IRONMEM_FILE_MAX_BYTES: usize = 24_000;
/// Ceiling on any single memory's summary within the file. A provider can
/// return a summary of any length, and one verbose session should not crowd
/// out four useful ones.
const IRONMEM_ENTRY_MAX_BYTES: usize = 4_000;

/// Describes successful file output; telemetry failure does not undo that output.
#[derive(Debug, Default, serde::Serialize)]
pub struct InjectionReport {
    pub written_ids: Vec<i64>,
    pub omitted: usize,
    pub bytes: usize,
    pub telemetry_recorded: bool,
}

pub fn render_memories(memories: &[Memory], budget: usize) -> (String, InjectionReport) {
    let mut report = InjectionReport {
        omitted: memories.len(),
        ..Default::default()
    };
    if memories.is_empty() {
        return (String::new(), report);
    }
    let mut text = "# IronMem — Session Memory\n> Auto-generated by ironmem. Do not edit manually.\n\n## Recent Session Context\n\n".to_string();
    let footer = |n| {
        format!("_{n} memories omitted to keep this file small. They remain searchable with `search_memories`._\n")
    };
    if text.len() + footer(memories.len()).len() > budget {
        return (String::new(), report);
    }
    for (i, memory) in memories.iter().enumerate() {
        let date = Utc
            .timestamp_opt(memory.created_at, 0)
            .single()
            .map(|dt| dt.format("%Y-%m-%d").to_string())
            .unwrap_or_else(|| "unknown".into());
        let summary = crate::strutil::truncate_bytes(&memory.summary, IRONMEM_ENTRY_MAX_BYTES);
        let tags = crate::strutil::truncate_bytes(memory.tags.as_deref().unwrap_or(""), 512);
        let entry = format!("### Session {} ({date}) · Memory {}\nMemory ID: {}. If a transcript is attached, expand through `retrieve_original` with `{{\"memory_id\":{}}}` (subject to authorization).\n{summary}\nKeywords: {tags}\n\n", i+1, memory.id, memory.id, memory.id);
        let remaining = memories.len() - report.written_ids.len() - 1;
        let reserve = if remaining > 0 {
            footer(remaining).len()
        } else {
            0
        };
        if text.len() + entry.len() + reserve > budget {
            break;
        }
        text.push_str(&entry);
        report.written_ids.push(memory.id);
    }
    report.omitted = memories.len() - report.written_ids.len();
    if report.omitted > 0 {
        text.push_str(&footer(report.omitted));
    }
    report.bytes = text.len();
    (text, report)
}

/// Replace in the same directory so readers see either complete version.
pub fn write_ironmem_file(project_root: &str, memories: &[Memory]) -> Result<InjectionReport> {
    use std::io::Write;
    let path = Path::new(project_root).join("IRONMEM.md");
    let (text, report) = render_memories(memories, IRONMEM_FILE_MAX_BYTES);
    if text.is_empty() {
        match std::fs::remove_file(&path) {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(e.into()),
        }
    } else {
        let mut temp = tempfile::NamedTempFile::new_in(project_root)?;
        temp.write_all(text.as_bytes())?;
        temp.as_file().sync_all()?;
        temp.persist(&path)?;
    }
    Ok(report)
}

/// Shared CLI/MCP delivery boundary: only successful inclusions earn events.
pub async fn inject_memories(
    db: &crate::db::Database,
    project: &str,
    memories: &[Memory],
) -> Result<InjectionReport> {
    ensure_claude_md_import(project)?;
    let mut report = write_ironmem_file(project, memories)?;
    let included: Vec<Memory> = memories
        .iter()
        .filter(|m| report.written_ids.contains(&m.id))
        .cloned()
        .collect();
    match crate::db::record_injection_events(db, project, None, Some("session-start"), &included)
        .await
    {
        Ok(()) => report.telemetry_recorded = true,
        Err(error) => {
            tracing::warn!(%error, "Context file written but injection telemetry was not recorded")
        }
    }
    Ok(report)
}

/// Ensure CLAUDE.md in the project root has an @IRONMEM.md import.
/// Appends it if missing. Does not duplicate if already present.
pub fn ensure_claude_md_import(project_root: &str) -> Result<()> {
    let claude_md_path = Path::new(project_root).join("CLAUDE.md");
    let import_line = "@IRONMEM.md";

    if claude_md_path.exists() {
        let content = std::fs::read_to_string(&claude_md_path)?;
        if content.contains(import_line) {
            return Ok(()); // Already imported
        }
        // Append the import
        let updated = if content.ends_with('\n') {
            format!("{}\n{}\n", content, import_line)
        } else {
            format!("{}\n\n{}\n", content, import_line)
        };
        std::fs::write(&claude_md_path, updated)?;
        tracing::info!("Added @IRONMEM.md import to CLAUDE.md");
    } else {
        // Create a minimal CLAUDE.md with just the import
        let content = format!("# Project Context\n\n{}\n", import_line);
        std::fs::write(&claude_md_path, content)?;
        tracing::info!("Created CLAUDE.md with @IRONMEM.md import");
    }

    Ok(())
}

/// Remove the @IRONMEM.md import from CLAUDE.md (used on wipe)
pub fn remove_claude_md_import(project_root: &str) -> Result<()> {
    let claude_md_path = Path::new(project_root).join("CLAUDE.md");
    if !claude_md_path.exists() {
        return Ok(());
    }

    let content = std::fs::read_to_string(&claude_md_path)?;
    let updated = content
        .lines()
        .filter(|line| !line.contains("@IRONMEM.md"))
        .collect::<Vec<_>>()
        .join("\n");

    std::fs::write(&claude_md_path, format!("{}\n", updated.trim_end()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn memory(id: i64, summary: &str) -> Memory {
        Memory {
            id,
            project: "/tmp/project".to_string(),
            session_id: format!("session-{id}"),
            summary: summary.to_string(),
            tags: Some("local-compression".to_string()),
            created_at: 1_700_000_000,
        }
    }

    fn temp_root(name: &str) -> std::path::PathBuf {
        let root =
            std::env::temp_dir().join(format!("ironmem-hooks-{name}-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn exact_budgets_keep_handles_and_cap_hostile_metadata() {
        let mut m = memory(i64::MAX, &"☃".repeat(10_000));
        m.tags = Some("✓".repeat(100_000));
        m.created_at = i64::MAX;
        let memories = vec![m; 12];
        for budget in [0, 1, 100, 2_000, 4_000, 24_000] {
            let (text, report) = render_memories(&memories, budget);
            assert!(text.len() <= budget);
            assert_eq!(text.len(), report.bytes);
            assert_eq!(report.omitted + report.written_ids.len(), 12);
            assert_eq!(
                text.matches("### Session ").count(),
                report.written_ids.len()
            );
            if !report.written_ids.is_empty() {
                assert!(text.contains("{\"memory_id\":9223372036854775807}"));
                assert!(text.contains("unknown"));
            }
        }
    }

    #[tokio::test]
    async fn delivery_events_match_output_and_failures_are_honest() -> Result<()> {
        use sqlx::Row;
        let root = tempfile::tempdir()?;
        let project = root.path().to_str().unwrap();
        let db = crate::db::Database::new(root.path().join("test.db").to_str().unwrap()).await?;
        db.migrate().await?;
        let memories: Vec<_> = (1..=12).map(|id| memory(id, &"x".repeat(10_000))).collect();
        let report = inject_memories(&db, project, &memories).await?;
        let ids: Vec<i64> = sqlx::query("SELECT memory_id FROM injection_events ORDER BY rank")
            .fetch_all(&db.pool)
            .await?
            .iter()
            .map(|r| r.get("memory_id"))
            .collect();
        assert_eq!(ids, report.written_ids);
        assert!(report.telemetry_recorded);
        assert!(report.omitted > 0);
        let empty = inject_memories(&db, project, &[]).await?;
        assert!(empty.written_ids.is_empty());
        assert!(!root.path().join("IRONMEM.md").exists());
        std::fs::create_dir(root.path().join("IRONMEM.md"))?;
        assert!(inject_memories(&db, project, &memories).await.is_err());
        let count: i64 = sqlx::query("SELECT COUNT(*) AS n FROM injection_events")
            .fetch_one(&db.pool)
            .await?
            .get("n");
        assert_eq!(count as usize, ids.len());
        std::fs::remove_dir(root.path().join("IRONMEM.md"))?;
        sqlx::query("DROP TABLE injection_events")
            .execute(&db.pool)
            .await?;
        let report = inject_memories(&db, project, &memories).await?;
        assert!(!report.telemetry_recorded);
        assert_eq!(
            std::fs::read(root.path().join("IRONMEM.md"))?.len(),
            report.bytes
        );
        db.pool.close().await;
        Ok(())
    }

    #[test]
    fn generated_file_stays_within_its_budget() {
        let root = temp_root("budget");
        let memories: Vec<Memory> = (0..12)
            .map(|i| memory(i, &"summary text ".repeat(400)))
            .collect();

        write_ironmem_file(root.to_str().unwrap(), &memories).unwrap();

        let written = std::fs::read_to_string(root.join("IRONMEM.md")).unwrap();
        assert!(
            written.len() <= IRONMEM_FILE_MAX_BYTES,
            "{} bytes",
            written.len()
        );
        assert!(written.contains("omitted to keep this file small"));
        assert!(written.contains("search_memories"));

        std::fs::remove_dir_all(&root).unwrap();
    }

    #[test]
    fn one_overlong_memory_is_truncated_but_still_written() {
        let root = temp_root("single");
        let memories = vec![memory(1, &"x".repeat(IRONMEM_ENTRY_MAX_BYTES * 3))];

        write_ironmem_file(root.to_str().unwrap(), &memories).unwrap();

        let written = std::fs::read_to_string(root.join("IRONMEM.md")).unwrap();
        assert!(written.contains("### Session 1"));
        assert!(written.contains("[truncated]"));
        assert!(!written.contains("omitted to keep this file small"));

        std::fs::remove_dir_all(&root).unwrap();
    }

    #[test]
    fn every_memory_is_written_when_all_of_them_fit() {
        let root = temp_root("fits");
        let memories = vec![memory(1, "first session"), memory(2, "second session")];

        write_ironmem_file(root.to_str().unwrap(), &memories).unwrap();

        let written = std::fs::read_to_string(root.join("IRONMEM.md")).unwrap();
        assert!(written.contains("first session"));
        assert!(written.contains("second session"));
        assert!(!written.contains("omitted to keep this file small"));

        std::fs::remove_dir_all(&root).unwrap();
    }
}
